AllCops:
  TargetRubyVersion: 2.7

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Naming/FileName:
  Enabled: true
  Exclude:
    - lib/resource-struct.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
